---
title: "User Interview"
output: pdf_document
date: "2024-05-29"
author: "Jacob Levin"
---

# What is a Fitbit?

A Fitbit is technology that tracks an user's every day physical health and bodily health. Fitbit comes as a physical wearable device that an user can wear along with an digital app to sync and record the data from the wearable device. Current forms of monitoring is free and accessible to all users; if users want to gain additional analytics or insights, they can pay a premium price to access more information. In addition to premium access to analytics or insight, some digital apps offer nutritional information and on-phone workout videos from professional fitness trainer (<https://www.womanandhome.com/health-and-wellbeing/how-to-set-up-a-fitbit-a-guide-206915/#:~:text=A%20Fitbit%20will%20automatically%20track,to%20download%20the%20Fitbit%20app.>).

# Why would a stakeholder use a Fitbit?

1.  Quality of life improvements via increaseing physical activities --- The stakeholder within this category are individuals with no or minimum experience in the gym who wants to reduce bad habits, build good habits, and sustain them in a busy environment with a Fitbit. On websites like reddit where users under r/Fitbit speak from personal anecdotes, the sentiment of lifestyle improvement and addressing laziness are key reasons to buy a Fitbit ([https://www.reddit.com/r/Fitbit/comments/c7tqk7/im_new_can_someone_explain_to_me_what_the_point/](https://www.reddit.com/r/fitbit/comments/c7tqk7/im_new_can_someone_explain_to_me_what_the_point/)).

2.  Tracking sleep --- Users who use Fitbit uses it to track overall trends or patterns in their sleep. However, professionals advise against using Fitbit to track the quality of sleep as the metrics and algorithm used in a Fitbit does not track REM or non-REM stages of sleeping. The technology fails to recgonize that everyone's sleeping patterns and habits may vary from the general public. For instance, an individual with a sleeping disorder has a different sleeping habit from the general population which the Fitbit fail to track. Stockholders may not have access to technology and professionals capable of performing a pornographically (PSG), a test used to diagnose sleeping disorder, opting for a more affordable alternative using a Fitbit. (**READ ARTICLE TO VERIFY THIS** [https://www.internationalsleepcharity.org/blog/what-i-learned-from-tracking-my-sleep-with-Fitbit-for-two-months](https://www.internationalsleepcharity.org/blog/what-i-learned-from-tracking-my-sleep-with-fitbit-for-two-months))

3.  Tracking calories --- A feature of Fitbit is to track calories burned. An application of the feature is managing weight loss. At the core of losing weight, an individual has to manage calories. Fitbit tracks calories by using basal metabolic rate combined withe personal information such as height, weight, sex, and age (<https://www.androidauthority.com/fitbit-calories-burned-3270477/>). A stakeholder of Fitbit may use the feature to manage weight loss via tracking calories since the technology is tailored towards the stakeholder. Fitbit is useful when comparing data (not limited to calories) between the present and yesterday, last week, last month or last year (<https://www.aber.ac.uk/en/news/archive/2019/01/title-220012-en.html>).

4.  Tracking heart-rate --- Tracking one's heart rate has numerous benefits to monitor any irregular activities. Stakeholders who use Fitbit has the ability to regularly check their heart rate and identify the state of their physical and emotional health (i.e. stress levels, hydration or fitness level) . High resting heart rate may raise concerns for stakeholders and notify them of irregular activities in their heart. (<https://www.sutterhealth.org/health/heart/get-to-know-your-heart-rate-it-might-save-your-life#:~:text=Keeping%20track%20of%20your%20heart,dehydration%2C%20inactivity%20and%20persistent%20stress.>)

With the reasons above in mind, it is crucial to conduct interviews to see how an average user (stakeholder) who uses Fitbit from the general population uses Fitbit. The goal of the interviews is to better understand what information truly matters to an user of the technology.

# Interview Questions

**NOTE:** All demographic information, if requested, can become anonymous to protect interviewee privacy.

**Informed consent and explanation for the project**

The project FitDashBoard aims to explore a better way of representing and inform an user's physical, mental, and emotional health. The project's end-goal is to produce a dashboard that helps users who are using or have used Fitbit (or similar devices) to better understand and communicate a user's health.

To better understand users of this technology, the interviewer will ask a series of questions starting with demographic information, Fitbit usage, and physical and mental health. To promote transparency within the data science community, the project, interview, and data will be publicly available online via GitHub. Questions related to demographic information can be completely anonymous such as name, age, occupation, level of physical activity, and disability status. The interview should take no longer then 45 minutes.

Does the interviewer have your explicit consent to interview you?

Interview 1: Yes

Interview 2: Yes

Interview 3: Yes

Interview 4: Yes

Interview 5: Yes

Is your participation in the interview voluntary?

Interview 1: Yes

Interview 2: Yes

Interview 3: Yes

Interview 4: Yes

Interview 5: Yes

**Demographic information**

1.  Name:
2.  Age:
3.  Occupation:
4.  Level of daily physical activity:
5.  Disability status (physical or mental):

**Fitbit usage**

1.  Have you ever used a Fitbit before? If so, what was the experience?

2.  What were features of the Fitbit app did you enjoy?

3.  Was there a time you have shown information from your Fitbit to a medical practitioner (i.e. doctor, physical therapist, etc.)? If so, why?

**Physical And Mental Health**

1.  What is important to your physical health when you are in a stressful environment?

2.  Imagine you are 50% away from achieving your physical goals, what information would you need to achieve your physical goals?

3.  Tell me about a time where you were motivated to stay physical throughout your day?

4.  Does counting the calories you burn matter to you? If so, how does a Fitbit device help you track the calories you burn?

5.  Was there ever a time where stress effected your sleeping pattern? If so, how did you correct your sleeping pattern?

6.  In what ways do you keep yourself motivated to correct your sleep schedule when it effects you negatively?

7.  How do you define success when you have corrected your sleeping schedule?

8.  If any, was there a time where you used physical indicators to assess your stress level (i.e. shortness of breath, fast heart rate or loss of appetite)? If so, how did you calm yourself down?

9.  Would you ever consider using sleep or heart rate as a method to gauge with your mental health?

10. Would knowing your heart rate impact your physical or mental health?

# Interviews

## **Interview 1**

**Demographic information**

1.  Name: Anonymous
2.  Age: Anonymous
3.  Occupation: Anonymous
4.  Level of daily physical activity: Anonymous
5.  Disability status (physical or mental): Anonymous

**Fitbit usage**

1.  Have you ever used a Fitbit before? If so, what was the experience?

I used a fitbit during high school. I didn't really use it a lot. I used it for the functionality as a watch. I used the exercise features a couple of times but in the end I didn't use it that much.

2.  What were features of the Fitbit app did you enjoy?

The time feature was the one I enjoyed. When I used the exercise features they were good such as counting steps and heart rate which I liked. i did not used the message feature.

3.  Was there a time you have shown information from your Fitbit to a medical practitioner (i.e. doctor, physical therapist, etc.)? If so, why?

No I never had a need.

**Physical And Mental Health**

1.  What is important to your physical health when you are in a stressful environment?

Advice that I should follow is do something physical. Finding a way to stay calm. Some means of taking your mind off the stress like doodling listening to music or taking a break and don't over work yourself.

2.  Imagine you are 50% away from achieving your physical goals, what information would you need to achieve your physical goals?

Mindset and then keep pushing by doing the same thing again. Don't stop making progress and be consistent. External help like friends has helped me out such as being in it together.

3.  Tell me about a time where you were motivated to stay physically throughout your day?

As an example, sports I did sports in middle and high school. You want to stay motivated and become better. Better was the motivation. I was doing tennis, weigh training, track.

4.  Does counting the calories you burn matter to you? If so, how does a Fitbit device help you track the calories you burn?

No, I just need to eat more. I never had to lose weight my issue was gaining weight. The feature on the Fitbit device was there but it never motivated me to do anything to lose weight.

5.  Was there ever a time where stress effected your sleeping pattern? If so, how did you correct your sleeping pattern?

The only time was studying for a test. The excitement and anxiety of going on a trip or doing something new but that stress was for one night. The solution to anxiety or stress I just prepare and face it head on.

6.  In what ways do you keep yourself motivated to correct your sleep schedule when it effects you negatively?

Take my internship, I dislike waking up early and I have experience issues with being an early bird. So, I solved it by creating a consistent routine by sleeping early. It was rough the first day but now I am better.

7.  How do you define success when you have corrected your sleeping schedule?

Using the internship example, there is no concrete definition of success. I guess in this case it is getting used to it, and following asleep at the same time.

8.  If any, was there a time where you used physical indicators to assess your stress level (i.e. shortness of breath, fast heart rate or loss of appetite)? If so, how did you calm yourself down?

I get stressed sometimes when I procrastinate such as writing a 16 page math paper. It was frustrating, I don't know if anger is the right word. I was physically fidgetting, touching my hair, or not being able sit still to do my work.

9.  Would you ever consider using sleep or heart rate as a method to gauge with your mental health? How would

Sleep and heart rate does help. Just being able to rest if your hear rate it too high then you would need exercise to help. I was would exercise to help with lowering heart rate and sleep to improve mental health.

10. Would knowing your heart rate impact your physical or mental health?

If it becomes a threat yes, I would change the way I live via self-care. The change wouldn't drastic but small.

**Follow-up interview**

1.  Are you open to a follow-up interview?

Yes.

## Interview 2

**Demographic information**

1.  Name: Anonymous
2.  Age: Anonymous
3.  Occupation: Anonymous
4.  Level of daily physical activity: Anonymous
5.  Disability status (physical or mental): Anonymous

**Fitbit usage**

1.  Have you ever used a Fitbit before? If so, what was the experience?

I have used a Fitbit before although the model is old but it still function. I have stopped using the Fitbit since the band gave me rashes. I thought the functions and features were good. I think the heart rate function is accurate but I doubt the sleep, water trackers, and calories are accurate. However, I think that it is good to know how long I have slept. I haven't used the alarm feature (since it's vibration is too small) Overall it was a good experience.

2.  What were features of the Fitbit app did you enjoy?

The breathing rate if it is accurate can be very useful but I doubt that it is accurate. However, it is an interesting feature. Step counter is nice and interesting but it is an overestimate. I don't know if it is inaccurate method of measuring my step due to my arms movement or my stride length.

3.  Was there a time you have shown information from your Fitbit to a medical practitioner (i.e. doctor, physical therapist, etc.)? If so, why?

I personally have not shown a doctor my data, but it might come up in my next doctor appointment since I have issues with sleeping.

**Physical And Mental Health**

1.  What is important to your physical health when you are in a stressful environment?

Being able to walk or move around, sometimes I like to walk when I am stress and especially during exams. I don't have a way of letting lose. I guess I can't say being alone because you can't be alone. I prefer to move around a little bit or work through the issue myself.

2.  Imagine you are 50% away from achieving your physical goals, what information would you need to achieve your physical goals?

Body fat percentage would be nice. I don't know how you would do it with a watch but that statistic would be more useful then BMI.

3.  Tell me about a time where you were motivated to stay physical throughout your day?

I guess one time was during school. Sometime I get worked up and go to the gym. It makes me feel productive and it is like doing something that impacts the future and to me it is something that productivity can be related to.

4.  Does counting the calories you burn matter to you? If so, how does a Fitbit device help you track the calories you burn?

Where they do have the exercise feature, they do have an option for lifting weights. So, I put the length of the workout and although I do have trouble recording intensity. The feature is a good way of measuring my workout.

5.  Was there ever a time where stress effected your sleeping pattern? If so, how did you correct your sleeping pattern?

Stress is probably inhibiting my ability to fall asleep. Stress also contributes to how many times I wake up or quality of sleep during school. It can kinda led into a bad spiral where you don't get enough sleep and you get tired. I guess stress does have a big impact on sleep quality.

6.  In what ways do you keep yourself motivated to correct your sleep schedule when it effects you negatively?

I guess it is the desire to not be miserable. I think not being tired helps me being more productive. If I am tired it is harder for me to understand lecture, mood, and productivity, when I am productive I have time to what I like. The motivation is productivity and more time to do what I like.

7.  How do you define success when you have corrected your sleeping schedule?

When I have consistent sleep for 2 weeks and the change in noticeable like more motivation and more energy in the afternoon.

8.  If any, was there a time where you used physical indicators to assess your stress level (i.e. shortness of breath, fast heart rate or loss of appetite)? If so, how did you calm yourself down?

I accurately don't have many physical indicator of stress. Maybe a little weakness. If I am stressed out and I will eat something, that will usually fix my stress levels.

9.  Would you ever consider using sleep or heart rate as a method to gauge with your mental health?

Yeah, I am not sure how heart rate measures mental health but sleeping does. Sleeping too much or too less would tell me about my mental health.

10. Would knowing your heart rate impact your physical or mental health?

I feel like it would impact my physical health since it is a measure of physical health. I'll probably use heart rate as a measure for physical health.

**Follow-up interview**

1.  Are you open to a follow-up interview?

Yes. Though I am not currently using Fitbit.

## Interview 3

**Demographic information**

1.  Name: Hayden Spector
2.  Age: 20
3.  Occupation: Student
4.  Level of daily physical activity: Between not really active and moderately active
5.  Disability status (physical or mental): Both physical and mental

**Fitbit usage**

1.  Have you ever used a Fitbit before? If so, what was the experience?

Yes, I have used Fitbit a couple years back. Ironically I used it to track my personal fitness. After I didn't feel a need for it, I stopped using it. After becoming disabled I started to use my apple watch to track my health.

2.  What were features of the Fitbit app did you enjoy?

I kinda felt that being able to see my step versus my friend's steps were fun.

3.  Was there a time you have shown information from your Fitbit to a medical practitioner (i.e. doctor, physical therapist, etc.)? If so, why?

I have shown my heart rate date to my doctor. When I was still using Fitbit, there wasn't information of heart rate. The doctors I have shown my heart rate data referred me to a cardiologist.

**Physical And Mental Health**

1.  What is important to your physical health when you are in a stressful environment?

Honestly, being able to eat or walk is the goal most of the time. Even though it is a low-bar, sometimes I can't do that.

2.  Imagine you are 50% away from achieving your physical goals, what information would you need to achieve your physical goals?

I feel like the probably is that my physical goal is related to my disability so there isn't a physical goal. There isn't a quantitative way of measuring my physical goal. I recently got knee braces which has been very helpful. Maybe tracking my heart rate would be useful but I have not done so in a while.

3.  Tell me about a time where you were motivated to stay physical throughout your day?

Last summer I was doing a lot of exercise and I had a gym membership.

4.  Does counting the calories you burn matter to you? If so, how does a Fitbit device help you track the calories you burn?

Honestly it doesn't really matter to me. Now I am at a health weight. In the past, it used to matter if I can eat enough to stay at a healthy weight.

5.  Was there ever a time where stress effected your sleeping pattern? If so, how did you correct your sleeping pattern?

Yeah especially during finals which effects my sleeping schedule. Honestly being able to come back home and not have finals helps my sleeping pattern. I also have a sleeping disorder.

6.  In what ways do you keep yourself motivated to correct your sleep schedule when it effects you negatively?

Honestly I just get tired all the time, and I sleep enough one day that it resets or I take a nap. If it gets to a point where I can't function, then I will shut down completely.

7.  How do you define success when you have corrected your sleeping schedule?

I would sleeping normal hours at night and not feeling completely exhausted in the morning. Extra win if I don't want to take a nap in the afternoon.

8.  If any, was there a time where you used physical indicators to assess your stress level (i.e. shortness of breath, fast heart rate or loss of appetite)? If so, how did you calm yourself down?

I don't think I ever used Fitbit explicitly, but I have used some functions on the apple watch to help me breathe.

9.  Would you ever consider using sleep or heart rate as a method to gauge with your mental health?

I don't think I would since my heart rate and sleep is already messed up from other things since there are too many variables to measure my mental health with sleep and heart rate.

10. Would knowing your heart rate impact your physical or mental health?

I would say physical. As I said knowing my heart rate impacts my knowledge of my physical health since I can avoid fainting and hitting my end.

**Follow-up interview**

1.  Are you open to a follow-up interview?

Yeah I will be fine with a follow-up interview.

## interview 4

**Demographic information**

1.  Name: Anonymous
2.  Age: Anonymous
3.  Occupation: Anonymous
4.  Level of daily physical activity: Anonymous
5.  Disability status (physical or mental): Anonymous

**Fitbit usage**

1.  Have you ever used a Fitbit before? If so, what was the experience?

Yes, I have used it before. If I had to give it a rating it would be 7/10, I don't think it was horrible but it did help me accomplish my goals and kept track of all of goals. It wasn't the most efficient and easily reliable device.

2.  What were features of the Fitbit app did you enjoy?

I really enjoyed how you could connect multiple Fitbit and show you how each model works. I don't remember too much. I remember it has all the basic features like step tracker. I would mainly use to the app to see if my device was connect. I don't have a reason to open up the app.

3.  Was there a time you have shown information from your Fitbit to a medical practitioner (i.e. doctor, physical therapist, etc.)? If so, why?

No I haven't.

**Physical And Mental Health**

1.  What is important to your physical health when you are in a stressful environment?

When i am in a stressful environment what is important is my water intake and my knowing my how many steps I taken which helps me in a stressful environment.

2.  Imagine you are 50% away from achieving your physical goals, what information would you need to achieve your physical goals?

I would like to have the same information I have when I was losing the first 50%. The basics like calories burned, water intake, how many steps I have been taking, and the duration of the workout. I don't' care a lot of about heart rate and other features.

3.  Tell me about a time where you were motivated to stay physical throughout your day?

I tend to be physical the most throughout my day when I have a good mindset. It is more about a mindset. I don't need a Fitbit or a gym to stay fit. If I have given motivate through words, I can get up and exercise.

4.  Does counting the calories you burn matter to you? If so, how does a Fitbit device help you track the calories you burn?

I do like keeping track of calories I have burned but I didn't see a function for it on the Fitbit I had.

5.  Was there ever a time where stress effected your sleeping pattern? If so, how did you correct your sleeping pattern?

Yes, there has been. The way I corrected it was pull an all-nighter and reset it the next day.

6.  In what ways do you keep yourself motivated to correct your sleep schedule when it effects you negatively?

My motivation to correct my sleeping schedule is when it effect my physical and mental health. To keep myself incheck, I will correct my sleeping schedule.

7.  How do you define success when you have corrected your sleeping schedule?

Just getting 8 hours of sleeping throughout the night at least. That is perfect for me. If I can wake up before 12:00 pm and go to bed before 4:00 am, my sleeping schedule would be perfect for me.

8.  If any, was there a time where you used physical indicators to assess your stress level (i.e. shortness of breath, fast heart rate or loss of appetite)? If so, how did you calm yourself down?

The physical things that helped me realize I have stress is acne, and loss of sleep. It was more so a mindset. I think for myself it was easier to calm myself down by talking to myself.

9.  Would you ever consider using sleep or heart rate as a method to gauge with your mental health?

Yeah, I would use sleep to gauge with my sleep. Sleep is part of my mental health. Heart rate is unpredictable so no.

10. Would knowing your heart rate impact your physical or mental health?

It would make me hyper-aware of situation so I would not like to use heart rate. I only need to look at my heart rate while working out. Knowing my heart rate 24/7 is not helpful.

**Follow-up interview**

1.  Are you open to a follow-up interview?

Yeah.

## Interview 5

**Demographic information**

1.  Name: Anonymous
2.  Age: Anonymous
3.  Occupation: Anonymous
4.  Level of daily physical activity: Anonymous
5.  Disability status (physical or mental): Anonymous

**Fitbit usage**

1.  Have you ever used a Fitbit before? If so, what was the experience?

I used one for maybe 5 years and 2 or possibly 3 different variation. The experience is pretty grant. I used it for running and alarm setting with my Fitbit.

2.  What were features of the Fitbit app did you enjoy?

It is nice having all the stats in one place and I don't have to click around and find everything. Since the update, things are difficult to find.

3.  Was there a time you have shown information from your Fitbit to a medical practitioner (i.e. doctor, physical therapist, etc.)? If so, why?

I have not.

**Physical And Mental Health**

1.  What is important to your physical health when you are in a stressful environment?

Getting good exercise and staying hydrate.

2.  Imagine you are 50% away from achieving your physical goals, what information would you need to achieve your physical goals?

Thinking really specifically, just keeping track of everything. If we were talking about running, I would track steps, mileage, etc.

3.  Tell me about a time where you were motivated to stay physical throughout your day?

It is not very difficult to stay motivated when I am with someone to run. Fitbit has a feature where they notify you on how many steps you need. It motivates me during the weekend to walk.

4.  Does counting the calories you burn matter to you? If so, how does a Fitbit device help you track the calories you burn?

No counting calories does not matter to me. It does not. I do not use that feature.

5.  Was there ever a time where stress effected your sleeping pattern? If so, how did you correct your sleeping pattern?

Many times, and I just waited until the stressful period was over.

6.  In what ways do you keep yourself motivated to correct your sleep schedule when it effects you negatively?

I think being effected negatively is a motivation to correct my sleeping schedule to sleep more.

7.  How do you define success when you have corrected your sleeping schedule?

When I can tell I have slept around 8 or more hours and when I am not tired after waking up.

8.  If any, was there a time where you used physical indicators to assess your stress level (i.e. shortness of breath, fast heart rate or loss of appetite)? If so, how did you calm yourself down?

Not any of the physical attributes mentioned. I don't use anything to calm myself down so no.

9.  Would you ever consider using sleep or heart rate as a method to gauge with your mental health?

I would say sleep and yes.

10. Would knowing your heart rate impact your physical or mental health?

Physical I guess because I can see my heart rate when I am running to see if it was a good run.

**Follow-up interview**

1.  Are you open to a follow-up interview?

Yeah if I am in town.

# Big Takeaways From The Interviews

The interviewees has not used fitbit or related devices currently. However, interviewees have used such devices either during high school or for an extended period of time (i.e. 5 years). Most users have positive experiences with the device as some statistics were believed to be more accurate when compared to others which helped some interviewees achieved their goals of improving their mental, physical and overall health.

Features such as step counter and heart rate were useful with some caveats. Step counter did not take stride length and arm movement into consideration; heart rate were inaccurate to some interviewees. Most interviewees enjoyed the feature that allowed them to compare themselves with their friends.

It is important to note that only one interviewee who is physically disabled has shown her device to a cardiologist. She only showed her heart rate information.

In a stressful environment majority of the interviewees resolve or reduce their stress levels with the following methods:

1.  Doing phyisocal activities (i.e. walking)
2.  Doodling
3.  Eating
4.  Listening to music
5.  Monitoring Water Intake
6.  Working the resolve the source of the stress itself

To stay motivated throughout a stressful time or environment, majority of the interviewee agreed that friends, athletic club or going to the gym helps them stay motivated. Mentally, interviewees remain motivated by staying consistent, being in the right mindset (words of affirmation), or being productive with their time. Outside of external and internal motivation, knowing and tracking their calories, water intake, steps, and duration of workout has helped them stay motivated.

Interviewees found that bad sleeping pattern occurs from stress before a test or final, anxiety, excitement, or being trapped in a bad sleeping pattern. Stress does inhibit sleep since stress contributes to the number of times interviewees wake up at night, and effects the quality of the sleep which can quickly become a negative cycle where stress causes bad sleeping patterns but bad sleeping patterns can cause stress. Interviewees find motivation to fix bad sleeping schedule interviewees by staying motivated with the desire to not feel mesirable, focus on productivity to have free time, or acknowledge the negative effects of bad sleeping schedule. Interviewees define a successful sleep schedule or pattern with constant sleep for a minimum 2 weeks, a sleeping schedule of 7-8 hours, more energy in the afternoon, not feeling exhausted, and no need for naps.

For the interviewee with a sleeping disorder, she fix her sleeping schedule by sleeping enough for one day. "Enough sleep" is subjective thus there is not a quantity for "enough sleep".

The physical indicators of stress that more interviewees found to indicate stress are listed below:

1.  Acne
2.  Fidgeting
3.  Loss of Sleep
4.  Overall Physical Weakness
5.  Not being able to sit still
6.  Procrastination
7.  Snacking
8.  Touching their own hair

Interviewee had mix of positive and negative responses for how sleep and heart rate are indicators for mental health. Mostly interviewees agreed that heart rate is a good indicator for physical health. The interviewee who is physically disabled stated that heart rate would be a good measurement to avoid fainting and being physically injured as a consequence.

# Work Citation (MLA 8)

**NOTE:** Due to R markdown file formatting and syntax proper MLA syntax can not be achieved.

"Home." *Get to Know Your Heart Rate: It Might Save Your Life*, www.sutterhealth.org/health/heart/get-to-know-your-heart-rate-it-might-save-your-life#:\~:text=Keeping%20track%20of%20your%20heart,dehydration%2C%20inactivity%20and%20persistent%20stress. Accessed 30 May 2024.

Imperial, Sleep. "What I Learned from Tracking My Sleep with Fitbit for Two Months." *International Sleep Charity*, 27 June 2020, www.internationalsleepcharity.org/blog/what-i-learned-from-tracking-my-sleep-with-fitbit-for-two-months. Accessed 29 May 2024.

"Is Your Fitbit Actually Counting Calories Correctly?" *Android Authority*, 17 May 2023, www.androidauthority.com/fitbit-calories-burned-3270477/. Accessed 30 May 2024.

Lim, Su Eun, et al. "Fitbit Inspire 2TM against Polysomnography in Adults: NSS." *Nature and Science of Sleep*, Dove Press, 28 Feb. 2023, www.dovepress.com/validation-of-fitbit-inspire-2tm-against-polysomnography-in-adults-con-peer-reviewed-fulltext-article-NSS#:\~:text=The%20sensitivity%20and%20specificity%20of,%25%2C%20respectively%20for%20REM%20sleep. Accessed 30 May 2024.

Lim, Su Eun, et al. "Fitbit Inspire 2TM against Polysomnography in Adults: NSS." *Nature and Science of Sleep*, Dove Press, 28 Feb. 2023, www.dovepress.com/validation-of-fitbit-inspire-2tm-against-polysomnography-in-adults-con-peer-reviewed-fulltext-article-NSS#:\~:text=The%20sensitivity%20and%20specificity%20of,%25%2C%20respectively%20for%20REM%20sleep. Accessed 30 May 2024.

*R/Fitbit on Reddit: I'm New. Can Someone Explain to Me What the Point of a Fitbit Is?*, www.reddit.com/r/fitbit/comments/c7tqk7/im_new_can_someone_explain_to_me_what_the_point/. Accessed 29 May 2024.

Walsh, Grace. "What Is a Fitbit and How Does It Work? Plus, Everything You Need to Know about Setting up Your Device." *Woman and Home Magazine*, Woman & Home, 14 Oct. 2022, www.womanandhome.com/health-and-wellbeing/how-to-set-up-a-fitbit-a-guide-206915/#:\~:text=A%20Fitbit%20will%20automatically%20track,to%20download%20the%20Fitbit%20app. Accessed 30 May 2024.
